# ----------------------------------------------------------------------------------------------------------------------
# Dubbo配置
# ----------------------------------------------------------------------------------------------------------------------
dubbo:
  application:
    name: "${spring.application.name}"
    parameters:
      "qos.enable": false
  protocol:
    name: "dubbo"
    port: "20880"
  registry:
    protocol: "zookeeper"
    address: "zk:2181"
    check: true
  config-center:
    address: "zk:2181"
    check: true
  provider:
    timeout: 1500
