# ----------------------------------------------------------------------------------------------------------------------
# Dubbo配置
# ----------------------------------------------------------------------------------------------------------------------
dubbo:
  application:
    name: "${spring.application.name}"
    parameters:
      "qos.enable": false
  registry:
    protocol: "zookeeper"
    address: "zk:2181"
    check: true
  config-center:
    address: "zk:2181"
    check: true
  consumer:
    check: false
    timeout: 1500
