dubbo:
  application:
    name: "${spring.application.name}"
    parameters:
      "qos.enable": false
  registry:
    protocol: "zookeeper"
    address: "127.0.0.1:2181"
  config-center:
    address: "127.0.0.1:2181"
    check: false
