dubbo:
  application:
    name: "${spring.application.name}"
    parameters:
      "qos.enable": false
#  protocol:
#    name: "dubbo"
#    port: "20880"
  registry:
    protocol: "zookeeper"
    address: "127.0.0.1:2181"
